### ISSUE TITLE
Class models info

### ISSUE THREAD

**Issue by nnamdei** [ahmedemad3965/Koshkie-Server#1]
Well done with this project. I have a few questions about some model classes in shops app.

- How dort the sort field work?
- there is a rely on class, what is it supposed to do?
- in the product model, there's a field for number sold and is_offer, please can you share your thoughts process here.
- what's your thoughts process on option model and option group.

**Comment by ahmedemad3965** [comment]
Hi namdi, I am glad that you read my code.

I will answer your questions now:

1. The sort field is like a relative id for the model, so instead of using normal database pk for the model to reference it (for example user would use the id 432214 for the third product in a shop), user will only use an id for the product relative to its parent container which is the shop. (for example you would use id 3 for that third product). It also allows the shop admin to easily change the order of their products.

2. for example If there is a sandwich product in a restaurant that has two option groups "Meal type" and "cola type" , and the "meal type" has two options "single" and "with cola", and the "cola type" has two options "sprite" and "Fanta". For the user to choose a "cola type" it has to choose a "meal type" with the "with cola" option, if they choose a "single", they can't choose "cola type", so the option group "cola type" relies on choosing a "meal type" with the "with cola" option.

3. the num_sold field is like a counter for how many times a product was ordered. is_offer field indicates whether a product is an offer or not, it's not very important. but many front end apps may use it for sending a notification about the offer and making it appear first in their menu.

4. option group and option are like key-value pairs, option group is like a name or a category for multiple options, for example a product may have an option groups called "size" with options "small", "medium", "large".

I hope I answered your questions clearly.

Ahmed Emad.
