### ISSUE TITLE
Cart and Payment gateway

### ISSUE THREAD

**Issue by nnamdei** [ahmedemad3965/Koshkie-Server#3]
Thank you for your response in the previous issue. I would like to know your thought process on integrating a payment gateway for the final order and how to implement push notification on this project

**Comment by ahmedemad3965** [comment]
- Payment gateway is a really good idea, there are many good python APIs for this like stripe, I may add it to this project in the future.

- Push notifications is also a good feature that I should add, push notifications can be implemented using web sockets, Django has an API for this "Django channels", I haven't tried it yet, However I would recommend using node.js for web sockets because it better at Real-time connections and notifications.

**Comment by nnamdei** [comment]
alright. thank you
